/* ===================================
   SPAIN LOCATIONS — Provinces & Municipalities
   Each province includes its major municipalities.
   =================================== */

export const SPAIN_PROVINCES = [
  "A Coruña", "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila",
  "Badajoz", "Barcelona", "Bizkaia", "Burgos",
  "Cáceres", "Cádiz", "Cantabria", "Castellón", "Ceuta", "Ciudad Real", "Córdoba", "Cuenca",
  "Gipuzkoa", "Girona", "Granada", "Guadalajara",
  "Huelva", "Huesca",
  "Illes Balears",
  "Jaén",
  "La Rioja", "Las Palmas", "León", "Lleida", "Lugo",
  "Madrid", "Málaga", "Melilla", "Murcia",
  "Navarra",
  "Ourense",
  "Palencia", "Pontevedra",
  "Salamanca", "Santa Cruz de Tenerife", "Segovia", "Sevilla", "Soria",
  "Tarragona", "Teruel", "Toledo",
  "Valencia", "Valladolid",
  "Zamora", "Zaragoza",
] as const;

export type Province = typeof SPAIN_PROVINCES[number];

export const MUNICIPALITIES: Record<Province, string[]> = {
  "A Coruña": [
    "A Coruña", "Santiago de Compostela", "Ferrol", "Narón", "Oleiros", "Arteixo", "Carballo", "Culleredo",
    "Cambre", "Ares", "Betanzos", "Ribeira", "Boiro", "Noia", "Cee", "Mugardos", "Pontedeume",
    "Cedeira", "Ortigueira", "Cariño", "As Pontes", "Curtis", "Ordes", "Melide", "Padrón",
    "Rianxo", "Negreira", "Santa Comba", "Laxe", "Malpica", "Sada", "Bergondo", "Miño",
    "Fene", "Muxía", "Dumbría", "Carnota", "Porto do Son", "A Pobra do Caramiñal", "Arzúa",
  ],
  "Álava": [
    "Vitoria-Gasteiz", "Llodio", "Amurrio", "Salvatierra", "Oyón", "Iruña Oka",
    "Zuia", "Ayala", "Campezo", "Añana", "Labastida", "Laguardia", "Elciego",
    "Artziniega", "Okondo", "Armiñón", "Peñacerrada", "Bernedo",
  ],
  "Albacete": [
    "Albacete", "Hellín", "Villarrobledo", "Almansa", "La Roda", "Caudete", "Tobarra",
    "Casas-Ibáñez", "Tarazona de la Mancha", "Madrigueras", "Munera", "Chinchilla de Monte-Aragón",
    "Elche de la Sierra", "Yeste", "Alcaraz", "Bonete", "Montealegre del Castillo",
    "Fuentealbilla", "Alpera", "Balazote", "Pozohondo", "Alcalá del Júcar",
  ],
  "Alicante": [
    "Alicante", "Elche", "Torrevieja", "Orihuela", "Benidorm", "Alcoy", "Elda", "San Vicente del Raspeig",
    "Denia", "Villena", "Petrer", "Novelda", "Santa Pola", "Crevillente", "Ibi", "Altea",
    "Calpe", "Jávea", "Villajoyosa", "Campello", "Aspe", "Pilar de la Horadada",
    "Muchamiel", "San Juan de Alicante", "Alfaz del Pi", "Benissa", "Teulada", "Ondara",
    "Pedreguer", "Onil", "Monóvar", "Sax", "Guardamar del Segura", "Rojales", "Callosa de Segura",
    "Almoradí", "Cox", "Dolores", "Catral", "Redován", "Monforte del Cid",
  ],
  "Almería": [
    "Almería", "Roquetas de Mar", "El Ejido", "Adra", "Níjar", "Vícar", "Huércal-Overa",
    "Berja", "Cuevas del Almanzora", "Vera", "Garrucha", "Mojácar", "Pulpí", "Carboneras",
    "Albox", "Olula del Río", "Macael", "Purchena", "Tabernas", "Dalías", "Fiñana",
    "Huércal de Almería", "Viator", "Pechina", "Gádor", "Alhama de Almería",
  ],
  "Asturias": [
    "Oviedo", "Gijón", "Avilés", "Siero", "Langreo", "Mieres", "Castrillón", "San Martín del Rey Aurelio",
    "Corvera de Asturias", "Villaviciosa", "Llanera", "Cangas de Onís", "Cangas del Narcea",
    "Laviana", "Llanes", "Navia", "Grado", "Ribadesella", "Pravia", "Piloña", "Lena",
    "Tineo", "Valdés", "Carreño", "Aller", "Vegadeo", "Tapia de Casariego", "Cudillero",
  ],
  "Ávila": [
    "Ávila", "Arévalo", "Arenas de San Pedro", "Las Navas del Marqués", "Candeleda",
    "El Tiemblo", "Cebreros", "Sotillo de la Adrada", "El Barco de Ávila", "Piedrahíta",
    "Madrigal de las Altas Torres", "Mombeltrán", "El Hoyo de Pinares",
  ],
  "Badajoz": [
    "Badajoz", "Mérida", "Don Benito", "Villanueva de la Serena", "Almendralejo", "Montijo",
    "Zafra", "Villafranca de los Barros", "Olivenza", "Jerez de los Caballeros", "Llerena",
    "Azuaga", "Castuera", "Villanueva del Fresno", "Guareña", "Santos de Maimona",
    "Fregenal de la Sierra", "Fuente de Cantos", "Talavera la Real", "La Albuera",
    "Puebla de la Calzada", "Lobón", "Calamonte", "Valverde de Leganés",
  ],
  "Barcelona": [
    "Barcelona", "Hospitalet de Llobregat", "Badalona", "Terrassa", "Sabadell", "Mataró",
    "Santa Coloma de Gramenet", "Cornellà de Llobregat", "Sant Boi de Llobregat", "Rubí",
    "Manresa", "Vilanova i la Geltrú", "Viladecans", "El Prat de Llobregat", "Granollers",
    "Cerdanyola del Vallès", "Mollet del Vallès", "Esplugues de Llobregat", "Gavà",
    "Sant Cugat del Vallès", "Castelldefels", "Sant Feliu de Llobregat", "Igualada",
    "Vic", "Berga", "Martorell", "Olesa de Montserrat", "Sitges", "Calella", "Premià de Mar",
    "Montgat", "Pineda de Mar", "Arenys de Mar", "Sant Adrià de Besòs", "Ripollet",
    "Barberà del Vallès", "Sant Andreu de la Barca", "Montcada i Reixac",
  ],
  "Bizkaia": [
    "Bilbao", "Barakaldo", "Getxo", "Portugalete", "Santurtzi", "Basauri", "Leioa",
    "Sestao", "Galdakao", "Durango", "Erandio", "Amorebieta-Etxano", "Mungia",
    "Gernika-Lumo", "Sopelana", "Bermeo", "Berango", "Lekeitio", "Ondarroa",
    "Derio", "Sondika", "Arrigorriaga", "Igorre", "Ermua", "Eibar", "Markina-Xemein",
  ],
  "Burgos": [
    "Burgos", "Miranda de Ebro", "Aranda de Duero", "Briviesca", "Medina de Pomar",
    "Villarcayo", "Lerma", "Salas de los Infantes", "Espinosa de los Monteros",
    "Roa", "Peñaranda de Duero", "Belorado", "Covarrubias", "Quintanar de la Sierra",
  ],
  "Cáceres": [
    "Cáceres", "Plasencia", "Navalmoral de la Mata", "Coria", "Trujillo", "Miajadas",
    "Moraleja", "Talayuela", "Jaraíz de la Vera", "Montehermoso", "Valencia de Alcántara",
    "Hervás", "Guadalupe", "Logrosán", "Zorita", "Garrovillas de Alconétar",
  ],
  "Cádiz": [
    "Cádiz", "Jerez de la Frontera", "Algeciras", "San Fernando", "El Puerto de Santa María",
    "Chiclana de la Frontera", "Sanlúcar de Barrameda", "La Línea de la Concepción",
    "Puerto Real", "Rota", "Arcos de la Frontera", "Barbate", "Conil de la Frontera",
    "Los Barrios", "Tarifa", "Ubrique", "Vejer de la Frontera", "Chipiona", "Medina-Sidonia",
    "Trebujena", "Villamartín", "Olvera", "Prado del Rey", "Alcalá de los Gazules",
  ],
  "Cantabria": [
    "Santander", "Torrelavega", "Castro-Urdiales", "Camargo", "Piélagos", "El Astillero",
    "Laredo", "Santa Cruz de Bezana", "Los Corrales de Buelna", "Santoña",
    "Reinosa", "Suances", "Noja", "Colindres", "San Vicente de la Barquera",
    "Comillas", "Ampuero", "Ramales de la Victoria", "Potes", "Cabezón de la Sal",
  ],
  "Castellón": [
    "Castellón de la Plana", "Vila-real", "Burriana", "Vinaròs", "La Vall d'Uixó",
    "Benicarló", "Onda", "Almassora", "Benicàssim", "Nules", "Oropesa del Mar",
    "Segorbe", "Peñíscola", "Alcora", "Betxí", "Lucena del Cid", "Morella",
    "Montanejos", "Jérica", "Soneja", "Vilafamés", "Cabanes", "Torreblanca",
    "Alcalà de Xivert", "Sant Mateu", "Traiguera", "Les Coves de Vinromà",
  ],
  "Ceuta": ["Ceuta"],
  "Ciudad Real": [
    "Ciudad Real", "Puertollano", "Tomelloso", "Alcázar de San Juan", "Valdepeñas",
    "Manzanares", "Daimiel", "Miguelturra", "Socuéllamos", "Campo de Criptana",
    "Bolaños de Calatrava", "La Solana", "Herencia", "Almodóvar del Campo",
    "Malagón", "Villanueva de los Infantes", "Almagro", "Moral de Calatrava",
    "Pedro Muñoz", "Santa Cruz de Mudela", "Calzada de Calatrava",
  ],
  "Córdoba": [
    "Córdoba", "Lucena", "Puente Genil", "Montilla", "Priego de Córdoba", "Cabra",
    "Baena", "Palma del Río", "Peñarroya-Pueblonuevo", "Pozoblanco", "Villanueva de Córdoba",
    "Aguilar de la Frontera", "La Rambla", "Fernán-Núñez", "Castro del Río",
    "Hinojosa del Duque", "Rute", "Montoro", "Bujalance", "Belalcázar",
  ],
  "Cuenca": [
    "Cuenca", "Tarancón", "Quintanar del Rey", "San Clemente", "Motilla del Palancar",
    "Las Pedroñeras", "Iniesta", "Huete", "Priego", "Villanueva de la Jara",
    "Minglanilla", "Landete", "Mota del Cuervo", "El Provencio", "Belmonte",
  ],
  "Gipuzkoa": [
    "Donostia-San Sebastián", "Irun", "Errenteria", "Eibar", "Zarautz", "Arrasate",
    "Hernani", "Tolosa", "Lasarte-Oria", "Hondarribia", "Azpeitia", "Azkoitia",
    "Bergara", "Andoain", "Oñati", "Pasaia", "Zumárraga", "Ordizia", "Beasain",
    "Legazpi", "Zumarraga", "Getaria", "Zumaia", "Deba", "Mutriku",
  ],
  "Girona": [
    "Girona", "Figueres", "Blanes", "Lloret de Mar", "Olot", "Salt", "Palafrugell",
    "Sant Feliu de Guíxols", "Roses", "Banyoles", "Torroella de Montgrí", "La Bisbal d'Empordà",
    "Palamós", "Platja d'Aro", "Ripoll", "Castelló d'Empúries", "Calonge", "Tossa de Mar",
    "L'Escala", "Cadaqués", "Puigcerdà", "Besalú", "Campdevànol", "Arbúcies",
  ],
  "Granada": [
    "Granada", "Motril", "Almuñécar", "Baza", "Loja", "Guadix", "Maracena", "Armilla",
    "Las Gabias", "Salobreña", "Atarfe", "Santa Fe", "Huétor Tájar", "La Zubia",
    "Pinos Puente", "Órgiva", "Monachil", "Alfacar", "Huétor Vega", "Cúllar Vega",
    "Ogíjares", "Alhama de Granada", "Iznalloz", "Dúrcal", "Cenes de la Vega",
    "Gójar", "Albolote", "Peligros", "Jun", "Pulianas", "Cájar",
  ],
  "Guadalajara": [
    "Guadalajara", "Azuqueca de Henares", "Alovera", "El Casar", "Cabanillas del Campo",
    "Sigüenza", "Molina de Aragón", "Marchamalo", "Villanueva de la Torre", "Yunquera de Henares",
    "Brihuega", "Pastrana", "Cifuentes", "Mondéjar", "Jadraque",
  ],
  "Huelva": [
    "Huelva", "Lepe", "Isla Cristina", "Almonte", "Moguer", "Ayamonte", "Bollullos Par del Condado",
    "Cartaya", "Aljaraque", "Punta Umbría", "La Palma del Condado", "Valverde del Camino",
    "Nerva", "Minas de Riotinto", "Aracena", "Gibraleón", "Palos de la Frontera",
    "San Juan del Puerto", "Trigueros", "Rociana del Condado", "Mazagón",
  ],
  "Huesca": [
    "Huesca", "Monzón", "Barbastro", "Jaca", "Fraga", "Sabiñánigo", "Binéfar", "Graus",
    "Tamarite de Litera", "Sariñena", "Ainsa", "Benasque", "Canfranc", "Ayerbe",
    "Castejón de Sos", "Boltaña", "Aínsa-Sobrarbe", "Alquézar",
  ],
  "Illes Balears": [
    "Palma", "Calvià", "Manacor", "Llucmajor", "Marratxí", "Inca", "Santa Eulària des Riu",
    "Eivissa", "Sant Josep de sa Talaia", "Sant Antoni de Portmany", "Maó-Mahón",
    "Ciutadella de Menorca", "Felanitx", "Pollença", "Alcúdia", "Sóller", "Sa Pobla",
    "Campos", "Santanyí", "Artà", "Andratx", "Capdepera", "Son Servera", "Santa Margalida",
    "Binissalem", "Muro", "Alaró", "Sineu", "Petra", "Porreres",
  ],
  "Jaén": [
    "Jaén", "Linares", "Andújar", "Úbeda", "Martos", "Baeza", "Alcalá la Real",
    "Torredonjimeno", "Alcaudete", "La Carolina", "Mancha Real", "Jódar",
    "Torredelcampo", "Villacarrillo", "Cazorla", "Bailén", "Porcuna",
    "Villanueva del Arzobispo", "Mengíbar", "Huelma", "Pozo Alcón", "Quesada",
  ],
  "La Rioja": [
    "Logroño", "Calahorra", "Arnedo", "Haro", "Lardero", "Alfaro", "Nájera",
    "Santo Domingo de la Calzada", "Villamediana de Iregua", "Pradejón", "Autol",
    "Fuenmayor", "Navarrete", "Ezcaray", "Cenicero", "San Asensio", "Albelda de Iregua",
  ],
  "Las Palmas": [
    "Las Palmas de Gran Canaria", "Telde", "Santa Lucía de Tirajana", "Arrecife",
    "San Bartolomé de Tirajana", "Arucas", "Puerto del Rosario", "Agüimes",
    "Ingenio", "La Oliva", "Gáldar", "Mogán", "Tías", "Antigua", "Pajara",
    "Valsequillo de Gran Canaria", "San Bartolomé", "Tuineje", "Teror", "Firgas",
    "Yaiza", "Haría", "Teguise", "Tinajo", "Moya", "Valleseco",
  ],
  "León": [
    "León", "Ponferrada", "San Andrés del Rabanedo", "Villaquilambre", "Astorga",
    "La Bañeza", "Villablino", "Bembibre", "Valencia de Don Juan", "Cistierna",
    "La Robla", "Cacabelos", "Sahagún", "Boñar", "Mansilla de las Mulas",
  ],
  "Lleida": [
    "Lleida", "Balaguer", "Tàrrega", "La Seu d'Urgell", "Mollerussa", "Cervera",
    "Les Borges Blanques", "Almacelles", "Solsona", "Tremp", "Sort", "El Pont de Suert",
    "Artesa de Segre", "Agramunt", "Bellpuig", "Guissona", "Vielha e Mijaran",
  ],
  "Lugo": [
    "Lugo", "Monforte de Lemos", "Viveiro", "Vilalba", "Sarria", "Foz", "Burela",
    "Chantada", "Ribadeo", "Mondoñedo", "Guitiriz", "Palas de Rei", "Outeiro de Rei",
    "Becerreá", "A Fonsagrada", "Quiroga", "O Corgo",
  ],
  "Madrid": [
    "Madrid", "Móstoles", "Alcalá de Henares", "Fuenlabrada", "Leganés", "Getafe",
    "Alcorcón", "Torrejón de Ardoz", "Parla", "Alcobendas", "Las Rozas de Madrid",
    "San Sebastián de los Reyes", "Pozuelo de Alarcón", "Coslada", "Rivas-Vaciamadrid",
    "Valdemoro", "Majadahonda", "Collado Villalba", "Aranjuez", "Arganda del Rey",
    "Boadilla del Monte", "Pinto", "Colmenar Viejo", "Tres Cantos", "San Fernando de Henares",
    "Galapagar", "Arroyomolinos", "Navalcarnero", "Ciempozuelos", "Villaviciosa de Odón",
    "Mejorada del Campo", "Torrelodones", "Villanueva de la Cañada", "Villanueva del Pardillo",
    "El Escorial", "San Lorenzo de El Escorial", "Chinchón", "Cercedilla", "Guadarrama",
    "Moralzarzal", "Hoyo de Manzanares", "Alpedrete", "Brunete", "Sevilla la Nueva",
  ],
  "Málaga": [
    "Málaga", "Marbella", "Mijas", "Vélez-Málaga", "Fuengirola", "Torremolinos",
    "Benalmádena", "Estepona", "Rincón de la Victoria", "Antequera", "Ronda",
    "Alhaurín de la Torre", "Alhaurín el Grande", "Cártama", "Coín", "Manilva",
    "Nerja", "Torrox", "Álora", "Archidona", "Campillos", "Ojén", "Casabermeja",
    "Algarrobo", "Frigiliana", "Cómpeta", "Tolox", "Yunquera",
  ],
  "Melilla": ["Melilla"],
  "Murcia": [
    "Murcia", "Cartagena", "Lorca", "Molina de Segura", "Alcantarilla", "Mazarrón",
    "Cieza", "Águilas", "Yecla", "Torre-Pacheco", "San Javier", "Totana",
    "Caravaca de la Cruz", "Jumilla", "San Pedro del Pinatar", "Las Torres de Cotillas",
    "Mula", "Alhama de Murcia", "Archena", "Cehegín", "Bullas", "Calasparra",
    "La Unión", "Fuente Álamo de Murcia", "Lorquí", "Beniel", "Blanca",
  ],
  "Navarra": [
    "Pamplona", "Tudela", "Barañáin", "Burlada", "Estella-Lizarra", "Zizur Mayor",
    "Tafalla", "Villava", "Ansoáin", "Berriozar", "Alsasua", "Corella",
    "Sangüesa", "Peralta", "Cintruénigo", "Fitero", "Cascante", "Olite",
    "Aoiz", "Elizondo", "Baztan", "Roncesvalles", "Puente la Reina",
  ],
  "Ourense": [
    "Ourense", "Verín", "O Barco de Valdeorras", "Carballiño", "Xinzo de Limia",
    "Celanova", "Allariz", "Ribadavia", "O Carballiño", "A Rúa",
    "Maceda", "Bande", "Monterrei", "Castro Caldelas",
  ],
  "Palencia": [
    "Palencia", "Aguilar de Campoo", "Guardo", "Venta de Baños", "Cervera de Pisuerga",
    "Dueñas", "Saldaña", "Carrión de los Condes", "Herrera de Pisuerga", "Paredes de Nava",
    "Osorno la Mayor", "Velilla del Río Carrión", "Alar del Rey",
  ],
  "Pontevedra": [
    "Vigo", "Pontevedra", "Vilagarcía de Arousa", "Redondela", "Cangas", "Marín",
    "Ponteareas", "Lalín", "Moaña", "Nigrán", "O Porriño", "Tui", "Gondomar",
    "Baiona", "Bueu", "Sanxenxo", "O Grove", "Cambados", "Vilanova de Arousa",
    "A Guarda", "A Estrada", "Silleda", "Forcarei", "Caldas de Reis",
  ],
  "Salamanca": [
    "Salamanca", "Béjar", "Santa Marta de Tormes", "Ciudad Rodrigo", "Carbajosa de la Sagrada",
    "Villares de la Reina", "Peñaranda de Bracamonte", "Alba de Tormes", "Guijuelo",
    "Vitigudino", "Lumbrales", "Ledesma", "La Alberca", "Candelario",
  ],
  "Santa Cruz de Tenerife": [
    "Santa Cruz de Tenerife", "San Cristóbal de la Laguna", "Arona", "Adeje",
    "La Orotava", "Los Realejos", "Granadilla de Abona", "Puerto de la Cruz",
    "Candelaria", "Tacoronte", "Güímar", "Santiago del Teide", "Icod de los Vinos",
    "San Miguel de Abona", "El Rosario", "Los Llanos de Aridane", "Tegueste",
    "Santa Úrsula", "San Sebastián de la Gomera", "Valverde", "Santa Cruz de la Palma",
  ],
  "Segovia": [
    "Segovia", "Cuéllar", "El Espinar", "San Ildefonso", "Cantalejo", "Carbonero el Mayor",
    "Nava de la Asunción", "Riaza", "Sepúlveda", "Ayllón", "Turégano",
    "Villacastín", "Coca", "Pedraza",
  ],
  "Sevilla": [
    "Sevilla", "Dos Hermanas", "Alcalá de Guadaíra", "Utrera", "Mairena del Aljarafe",
    "Écija", "La Rinconada", "Los Palacios y Villafranca", "Carmona", "Bormujos",
    "Camas", "Coria del Río", "Tomares", "San Juan de Aznalfarache", "Osuna",
    "Marchena", "Morón de la Frontera", "Lebrija", "Arahal", "Castilleja de la Cuesta",
    "Gines", "Estepa", "Las Cabezas de San Juan", "La Puebla del Río",
    "Sanlúcar la Mayor", "Olivares", "Guillena", "Brenes", "Lora del Río",
    "Espartinas", "La Algaba", "Gelves", "Pilas", "Mairena del Alcor",
  ],
  "Soria": [
    "Soria", "Almazán", "El Burgo de Osma", "Ólvega", "San Esteban de Gormaz",
    "Ágreda", "Arcos de Jalón", "Medinaceli", "San Leonardo de Yagüe", "Covaleda",
    "Vinuesa", "Berlanga de Duero",
  ],
  "Tarragona": [
    "Tarragona", "Reus", "El Vendrell", "Cambrils", "Tortosa", "Salou", "Valls",
    "Vila-seca", "Amposta", "Calafell", "Sant Carles de la Ràpita", "Torredembarra",
    "La Bisbal del Penedès", "Cunit", "Montblanc", "Roquetes", "Falset",
    "El Morell", "Altafulla", "Constantí", "L'Arboç", "Gandesa", "Deltebre",
  ],
  "Teruel": [
    "Teruel", "Alcañiz", "Andorra", "Calamocha", "Utrillas", "Calanda", "Valderrobres",
    "Albarracín", "Mora de Rubielos", "Monreal del Campo", "Cella", "Sarrión",
    "Montalbán", "Híjar", "Mas de las Matas", "Castellote", "Rubielos de Mora",
    "Puertomingalvo", "Cantavieja", "La Iglesuela del Cid", "Mirambel",
  ],
  "Toledo": [
    "Toledo", "Talavera de la Reina", "Illescas", "Seseña", "Torrijos", "Sonseca",
    "Mora", "Consuegra", "Madridejos", "Quintanar de la Orden", "Villacañas",
    "Ocaña", "Fuensalida", "La Puebla de Montalbán", "Yuncler", "Bargas",
    "Olías del Rey", "Añover de Tajo", "Miguel Esteban", "El Toboso",
    "Tembleque", "Orgaz", "Esquivias", "Yuncos", "Numancia de la Sagra",
  ],
  "Valencia": [
    "Valencia", "Torrent", "Gandía", "Paterna", "Sagunto", "Alzira", "Mislata",
    "Burjassot", "Ontinyent", "Manises", "Xàtiva", "Aldaia", "Alfafar",
    "Quart de Poblet", "Sueca", "Catarroja", "Cullera", "Requena", "Utiel",
    "Alaquàs", "Bétera", "Oliva", "Llíria", "Picassent", "Silla", "Paiporta",
    "Alboraya", "Massanassa", "Tavernes de la Valldigna", "L'Eliana", "Carcaixent",
    "La Pobla de Vallbona", "Algemesí", "Puçol", "Moncada", "Godella", "Rocafort",
    "Chiva", "Buñol", "Xirivella", "Beniparrell", "Sedaví", "Picanya", "Albal",
  ],
  "Valladolid": [
    "Valladolid", "Medina del Campo", "Laguna de Duero", "Arroyo de la Encomienda",
    "Tordesillas", "Íscar", "Peñafiel", "Tudela de Duero", "Simancas",
    "Olmedo", "Pedrajas de San Esteban", "Cigales", "Mayorga", "Villalón de Campos",
    "Medina de Rioseco", "Portillo",
  ],
  "Zamora": [
    "Zamora", "Benavente", "Toro", "Morales del Vino", "Puebla de Sanabria",
    "Villalpando", "Bermillo de Sayago", "Fuentesaúco", "Alcañices",
    "Corrales del Vino", "Fermoselle", "Moraleja del Vino",
  ],
  "Zaragoza": [
    "Zaragoza", "Calatayud", "Utebo", "Ejea de los Caballeros", "Tarazona",
    "La Almunia de Doña Godina", "Caspe", "Zuera", "Cuarte de Huerva",
    "María de Huerva", "Alagón", "Borja", "Illueca", "Daroca", "Mallén",
    "Épila", "Fuentes de Ebro", "La Puebla de Alfindén", "Pedrola",
    "Cadrete", "Gallur", "Figueruelas", "Sos del Rey Católico", "Uncastillo",
  ],
};
